version: "3.8"

services:
  app:
    build: .
    container_name: sarahs-store-1
    ports:
      - "3000:3000"
    volumes:
      - ./db:/sarahs-store-docker/db
    command:
      - rails
      - server
      - -p
      - "3000"
      - -b
      - "0.0.0.0"
