name: tests
on: [push]

jobs: 
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake spec